<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Karthick" failures="2" tests="2" name="Test(failed)" time="0.034" errors="0" timestamp="20 Feb 2023 09:46:04 GMT">
  <testcase classname="com.testngInterview.TestCasess" name="testcase1" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.testngInterview.TestCasess.testcase1(TestCasess.java:9)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="com.testngInterview.TestCasess" name="testcase2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.testngInterview.TestCasess.testcase2(TestCasess.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- Test(failed) -->
